### ISSUE TITLE
Wrong behavior in Firefox with long sub-modal

### ISSUE THREAD

**Issue by pavel-mironchik** [javisperez/vuedals#1]
Hello.
I use your jsfiddle example (by the way, it not works after breaking change with `props` in 1.3.0) and added long sub-modal. Here is my example: https://jsfiddle.net/brunen9/qrt5gawh/

Press "New Modal" button, then press "Open another modal" button, scroll to the bottom and press "Close" button. In Firefox you will not see first modal. Now scroll mouth wheel up about 10 times and first modal will appear from top. But in Chrome and Safari first modal will appear immediately after sub-modal closing.

Can you please fix this?

**Comment by javisperez** [comment]
Hey @brunen9 thank you for your issue :) and for reporting the broken jsFiddle demo, I've updated the README.md file with the proper jsFiddle fixed link, thanks again!

About your bug, it's a weird bug, seems to be related on how Firefox is handling the scrollbar, I'll have a look later today and try to get it fixed by this weekend :). I'll update this issue when done. Thank you again!

**Comment by javisperez** [comment]
This has been fixed now. Seems like it was related to how Firefox handles rendering of 'out of view' absolute positioned elements.

Please feel free to test now, just keep in mind that the `cdn.rawgit.com` cache might be pointing to the previous release. You can point the `vuedals.min.js` file to the `https://cdn.rawgit.com/javisperez/vuedals/v1.3.1/dist/vuedals.min.js` to test the fix.

**Comment by pavel-mironchik** [comment]
It works good now. In my own project I went little further and save `scrollTop` value before adding each new modal in `modal.scrollTop` property. And after delete each modal I restore `scrollTop` from this saved value. Thereby, each modal "remembers" its scrolled position and UI looks more native.

**Comment by javisperez** [comment]
Hey that's actually a great idea, I'll try to implement it in the library natively, as an option, thanks for that idea :D I'll update this issue when I get it done :)
