### ISSUE TITLE
Feature request: keyboard control to close the modal

### ISSUE THREAD

**Issue by alsciende** [javisperez/vuedals#10]
This plugin is awesome, thank you. I have a small feature request: close the modal window when a key is pressed, by default 'Esc'. That's a standard feature for modal windows and I'm really missing it.

**Comment by javisperez** [comment]
Hey thanks for the issue! I've been considering this too, I'll have a look at it later today, thank you!

**Comment by javisperez** [comment]
@Alsciende I've added an `escapable` option, by default is false to prevent drastic changes on the users already using Vuedals as it was, so, just set `escapable: true` and should be able to dismiss the modal by using the escape key.

Thank you for the issue!
