### ISSUE TITLE
escapable fires on all key-events

### ISSUE THREAD

**Issue by mavuio** [javisperez/vuedals#15]
when i set escapable:true, the modal gets closed on all key-presses, not only
by pressing Escape.

**Comment by javisperez** [comment]
Damn it! I'm sorry, stupid me >.< I'm gonna fix this (with the help of your PR) asap. Thank you for letting me know! 👍

**Comment by javisperez** [comment]
Ok I've release a 1.6.1 which should fix this now, I'm sorry for the troubles.
