### ISSUE TITLE
Weird behaviour of <select> tag in Firefox

### ISSUE THREAD

**Issue by pavel-mironchik** [javisperez/vuedals#18]
Hello.
Please look at this [jsfiddle](https://jsfiddle.net/qrt5gawh/1/).

Press `New Modal` button, then try to select anything from select input. In Firefox the list with selectable options will appear not right under select input, but far to right side. In Chrome select input works normal.

**Comment by javisperez** [comment]
Hello, thanks for the issue and especially the jsfiddle.

I've checked your example but everything works fine for me on Firefox 55.0.3, I've even added more options to the <select> in case it was a height related problem, but everything seems ok to me:

![image](https://user-images.githubusercontent.com/4766570/30220573-ecf664f2-948d-11e7-903f-ed6144fa18a6.png)

Just in case, can you please validate what version of Firefox are you using? Also, here's the same fiddle with three more options added: j[sfiddle](https://jsfiddle.net/qrt5gawh/2/).

**Comment by pavel-mironchik** [comment]
Whoa! I use the same version of Firefox. Your answer forced me to check my jsfiddle in newly created firefox profile... a-a-and it works fine!
Ha-ha, it seems that one of installed extensions breaks down behavior of select tag in modal. Sorry for disturbing you. At first I asked my colleague to check jsfiddle from his computer and he confirmed the "bug". If you don't mind, I will find what extension does this and will add its name in comment later.

**Comment by javisperez** [comment]
ohh great, thank you! and btw sorry! I've just noticed that my screenshot didn't upload, sorry for that :D. I'll close this comment now and wait for your extension feedback.

Thank you!

**Comment by pavel-mironchik** [comment]
It turned out that this was [Super Drag](https://addons.mozilla.org/en-US/firefox/addon/super-drag/) extension. It was last updated in 2014 and not compatible with new Firefox.
