### ISSUE TITLE
Avoid using non-primitive value as key, use string/number value instead.

### ISSUE THREAD

**Issue by chosten** [javisperez/vuedals#2]
Hello,
This component cause a warning to be raised because your are assigning a non-primitive key to the .vudal divs.
I don't think the reference is used so I believe it's safe to simply remove the assignation.

**Comment by javisperez** [comment]
Hey, thank you for opening this issue, sadly I can't remove the key for the `v-for` directive as is a good practice, but I can change it to prevent the warning.

**Comment by SRichner** [comment]
Any update on this? Getting the same error whenever a modal opens.
Thanks in advance :)

**Edit:** not sure if changing it to `:key="index"` would be already sufficient. The error message doesn't appear anymore locally (sorry, not sure how to make a pull request).

**Comment by DanielPe05** [comment]
Using the index as `:key` fixes this issue. I opened PR #4 for it.

**Comment by javisperez** [comment]
Hey @DanielPe05 thank you for the PR, I'm gonna check it right now! :) sorry for the delay, been a busy time for me, sorry guys.

**Comment by javisperez** [comment]
Ok, the new release have the fix @DanielPe05 implemented, should be as easy as just updating the package :) @SRichner. Here's the new release just in case: https://github.com/javisperez/vuedals/releases/tag/v1.4.0

**Comment by SRichner** [comment]
Thank you @javisperez!

**Comment by Satyamrao** [comment]
The issue resolved when we use `index` as the `:key` value
