### ISSUE TITLE
closing modal when click on background

### ISSUE THREAD

**Issue by anzolo** [javisperez/vuedals#22]
```
Vuedals.$emit("new", {
      title: title,
      dismissable: false,
      escapable:false,
      component: ccForm,
      props: {
        config: config
      },
      onClose(answer) {
        console.log("answer: ", answer);
      }
    });
```

1. modal open
2. user clicks to dark background around modal
3. modal close

How to make the modal not closed?

**Comment by javisperez** [comment]
Hey @anzolo thank you for your issue. There's actually no way to prevent the modal from closing when the backdrop is clicked (my fail!) but I can add this as an option (e.g. closeOnBackdrop="false") if you give me a few days. I'm really busy lately but should be small enough to do it quickly :)

**Comment by anzolo** [comment]
@javisperez Thank you for quick response! option will be the good solution.
