### ISSUE TITLE
Pass a slot to a modal?

### ISSUE THREAD

**Issue by antony-k1208** [javisperez/vuedals#23]
Hi there,

im trying to build a wrapper modal component, which uses vuedals for showing the passed content. I've built a very basic example in the following jsfiddle: https://jsfiddle.net/Lju6y0vz/1/.

Is there any way to pass the slots content to vuedals open function in order to achieve the desired behaviour? Or is there any other way to do this?

Thanks in advance.

Cheers, 
antony

**Comment by antony-k1208** [comment]
I think i've found a solution: https://jsfiddle.net/voguktb4/1/.
Instead of using the template logic, i'm working directly with the render function.

**Comment by javisperez** [comment]
Hey @antony-k1208 thank you for the issue and for the reply! Yeah, definitely the render function would be the way to go, as didn't expect slots to be used when made this library, sorry about that.

Closing this now as i think you solved your answer yourself :), would reopen later if needed.
