### ISSUE TITLE
How to close a specific vuedals?

### ISSUE THREAD

**Issue by msonowal** [javisperez/vuedals#9]
How to close a specific vuedals?
I have a situation where I am showing mutliple instances of vuedals one over another but I want close/remove some specific vuedals, so is it possible?

**Comment by javisperez** [comment]
Oh yikes! It was possible but I dumbly removed it, I'll re-add it later today and will update this same issue to let you know, sorry for the problems! and thanks for letting me know :)

**Comment by msonowal** [comment]
@javisperez  thats sounds great! let me know If I can help

**Comment by msonowal** [comment]
@javisperez I am waiting for you magic

**Comment by javisperez** [comment]
Hey @msonowal sorry for the delay (again) I've release a new version (1.6.0) which adds the option to pass a `$index` property to the data when closing or dismissing a modal. The `$index` propery can be a function or a number (the index of the modal to close). If it's a function, then the index of the current modal is passed and should return the index to close. 

For more info or example please feel free to check the readme and thank you for opening an issue! :)
